### ISSUE TITLE
CSS included in build -- css.js not found and link tags still generated

### ISSUE THREAD

**Issue by bsander** [guybedford/require-css#74]
After I build my application, all CSS is correctly loaded with an inline `<style>` tag, however, there are also `<link>` tags generated with references to the original css files (which are not available in my build dir). and requireJS complains about failing to load `css.js`. So while the script-inlined CSS correctly loads,  This results in some 404 errors after building my app. None of these files should be necessary after the CSS has been inlined, so how do I get rid of these requests?

This is what my chrome console shows:

![Screen Shot 2013-04-27 at 18 05 42 ](https://f.cloud.github.com/assets/517850/434587/db7f40a4-af54-11e2-8d06-7da4486a1a74.png)

![Screen Shot 2013-04-27 at 18 05 17 ](https://f.cloud.github.com/assets/517850/434586/db8068bc-af54-11e2-8928-0dab78c0aea5.png)

**Comment by IvoPereira** [comment]
Writing a dependency on config solved me the problem either!

Thanks!

**Comment by emahfoud** [comment]
I'm pretty new to using requirejs and I guess I'm missing a key point of some sort. None of the previous solutions worked for me. I get a combined file, which includes the config at the top as the first entry, and the inlined css at the very end. The resulting module still inserts a link to the unneeded original css file, but everything works as expected because the css is also inserted as a style element.

I'm not entirely sure what extra info I can attach.

**Comment by emahfoud** [comment]
I'm might be missing a key point of some sort. None of the previous solutions worked for me. I get a combined file, which includes the config at the top as the first entry, and the inlined css at the very end. The resulting module still inserts a link to the unneeded original css file, although its content is added to the page as a `<style>` element. 

The module I'm developing is a widget to be used by an already existing framework, so it is not a full application on its own.

I'm not entirely sure what extra info I can attach.
